<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <UseWindowsForms>false</UseWindowsForms>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <EnableDefaultNoneItems>false</EnableDefaultNoneItems>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputType>Library</OutputType>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <DefineConstants>NETSTANDARD</DefineConstants>
    <SignAssembly>True</SignAssembly>
    <AssemblyOriginatorKeyFile>C:\VSPath\KoCom\KoComNewDLL\StrongNameKey\KoCom-SN.pfx</AssemblyOriginatorKeyFile>
  </PropertyGroup>
  <ItemGroup>
    <Folder Include="Properties\" />
    <CSFile Include="*.cs" Exclude="obj\**\.cs" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="x64\*.dll" Pack="true" PackageCopyToOutput="true" PackagePath="x64">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="x86\*.dll" Pack="true" PackageCopyToOutput="true" PackagePath="x86">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Tesseract.targets" Pack="true" PackageCopyToOutput="true" PackagePath="build/">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <None Update="tessdata\deu.traineddata">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="x64\tesseract.exe">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
