<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWindowsForms>false</UseWindowsForms>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputType>Library</OutputType>
    <RootNamespace>Tesseract</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\Tesseract\BitmapToPixConverter.cs" Link="BitmapToPixConverter.cs" />
    <Compile Include="..\Tesseract\PixConverter.cs" Link="PixConverter.cs" />
    <Compile Include="..\Tesseract\PixToBitmapConverter.cs" Link="PixToBitmapConverter.cs" />
    <Compile Include="..\Tesseract\TesseractDrawingExtensions.cs" Link="TesseractDrawingExtensions.cs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" Version="6.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Tesseract\Tesseract.csproj" />
  </ItemGroup>
</Project>
